bundle:
    name: GoogleCustomSearchBundle
    description: Add Google Custom Search feature in BackBee
    author: Charles Rouillon <charles.rouillon@lp-digital.fr>
    version: 1.0
    enable: true
    thumbnail: /%bbapp.routing.resource_uri_prefix%/img/contents/picto-extnd-gcse.png
    config_per_site: true
    admin_controller:
        admin: LpDigital\Bundle\GoogleCustomSearchBundle\Controller\AdminController
    admin_entry_point: admin.index

gcse:
    developer_key: ~
    default_parameters:
        cx: ~
        queryParameterName: q
        resultsUrl: ~
        resultSetSize: large
        autoSearchOnLoad: true
        enableAutoComplete: true
        disableWebSearch: ~
        enableImageSearch: ~
